language: go

go:
  - 1.2.1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qy python-software-properties
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qy build-essential curl gcc-4.7 g++-4.7 libsnappy-dev libbz2-dev zlib1g-dev
  - sudo rm /usr/bin/gcc && sudo ln -s /usr/bin/gcc-4.7 /usr/bin/gcc
  - sudo rm /usr/bin/g++ && sudo ln -s /usr/bin/g++-4.7 /usr/bin/g++
  - curl -s https://gflags.googlecode.com/files/gflags-2.0-no-svn-files.tar.gz | tar -xzv
  - cd gflags-2.0/ && ./configure && make && sudo make install && cd .. && rm -rf gflags-2.0*
  - go get code.google.com/p/biogo.store/llrb
  - go get code.google.com/p/go-commander
  - go get code.google.com/p/go-uuid/uuid
  - go get github.com/golang/glog
  - go get gopkg.in/yaml.v1

install:
  - make build

script:
  - make test
