language: go

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qy python-software-properties
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq gcc-4.8 g++-4.8 libprotobuf-dev protobuf-compiler
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  - export PATH=$PATH:$HOME/gopath/bin

install:
  - ./bootstrap.sh
  - make build GOFLAGS=-x

script:
  - make test TESTFLAGS="-logtostderr -timeout 30s"
  - make testrace

notifications:
  email:
    recipients:
      - cockroach-db@googlegroups.com
    on_success: change
    on_failure: always
