language: go

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qy python-software-properties
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq gcc-4.8 g++-4.8 zlib1g-dev libbz2-dev libsnappy-dev libjemalloc-dev libprotobuf-dev protobuf-compiler
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  - wget https://gflags.googlecode.com/files/libgflags0_2.0-1_amd64.deb
  - sudo dpkg -i libgflags0_2.0-1_amd64.deb
  - wget https://gflags.googlecode.com/files/libgflags-dev_2.0-1_amd64.deb
  - sudo dpkg -i libgflags-dev_2.0-1_amd64.deb
  - wget https://protobuf.googlecode.com/files/protobuf-2.5.0.tar.bz2
  - bunzip2 protobuf-2.5.0.tar.bz2
  - tar xvf protobuf-2.5.0.tar
  - cd protobuf-2.5.0 && ./configure && make && sudo make install && cd ../
  - go get code.google.com/p/biogo.store/llrb
  - go get code.google.com/p/go-commander
  - go get code.google.com/p/go-uuid/uuid
  - go get code.google.com/p/go-uuid/uuid
  - go get code.google.com/p/gogoprotobuf/{proto,protoc-gen-gogo,gogoproto}
  - go get github.com/golang/glog
  - go get gopkg.in/yaml.v1

install:
  - make build

script:
  - make test

notifications:
  email:
    recipients:
      - cockroach-db@googlegroups.com
    on_success: change
    on_failure: always
