language: go

go:
  - 1.2.1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsnappy-dev zlib1g-dev libbz2-dev
  - wget https://gflags.googlecode.com/files/gflags-2.0-no-svn-files.tar.gz
  - tar -xzvf gflags-2.0-no-svn-files.tar.gz
  - cd gflags-2.0
  - ./configure && make && sudo make install && cd ..
  - go get code.google.com/p/biogo.store/llrb
  - go get code.google.com/p/go-commander
  - go get code.google.com/p/go-uuid/uuid
  - go get github.com/golang/glog
  - go get gopkg.in/yaml.v1

install:
  - make build

script:
  - make test
